stages:
  - prepare
  - build
  - test

variables:
    SHA_IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
    CMAKE_OPTIONS: "-DBUILD_DOCS=ON -GNinja"

cache:
  paths:
    - ccache
    - 3rdparty
# --------------------------------------------------------------------------------

devel-container:
  stage: prepare
  image: docker:19.03
  tags: ['docker-runner']
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $SHA_IMAGE_TAG -f build-environment.Dockerfile .
    - docker push $SHA_IMAGE_TAG
  only: [merge_requests]

# --------------------------------------------------------------------------------

compile:
  stage: build
  image: $SHA_IMAGE_TAG
  tags: ['docker-runner']
  artifacts:
    expire_in: 1 hr
    paths:
      - build
  # Use ccache transparently, and print stats before/after
  before_script:
    - export CCACHE_BASEDIR="$PWD"
    - export CCACHE_DIR="$PWD/ccache"
    - export CCACHE_COMPILERCHECK=content
    - ccache --zero-stats || true
    - ccache --show-stats || true
  script:
    - mkdir -p build
    - cd build
    - cmake $CMAKE_OPTIONS ..
    - ninja
  after_script:
    - export CCACHE_DIR="$PWD/ccache"
    - ccache --show-stats
  only: [merge_requests]

# --------------------------------------------------------------------------------

unit-tests:
  stage: test
  image: $SHA_IMAGE_TAG
  tags: ['docker-runner']
  script:
    - cd build
    - ninja test
  only: [merge_requests]
  artifacts:
    expire_in: 4 weeks
    name: docs
    paths:
      - build/docs/html/
