macro(BuildZlib)
  if (WIN32)
    list(APPEND ZLIB_LIBS_LIST_RELEASE "lib/zlib.lib")
    list(APPEND ZLIB_LIBS_LIST_DEBUG   "lib/zlibd.lib")
    list(APPEND ZLIB_DLLS_LIST_RELEASE "bin/zlib.dll")
    list(APPEND ZLIB_DLLS_LIST_DEBUG   "bin/zlibd.dll")
  elseif (APPLE)
    list(APPEND ZLIB_LIBS_LIST_RELEASE "lib/libz.dylib.1.2.11")
    list(APPEND ZLIB_LIBS_LIST_DEBUG   "")
    list(APPEND ZLIB_DLLS_LIST_RELEASE "")
    list(APPEND ZLIB_DLLS_LIST_DEBUG   "")
  else()
    list(APPEND ZLIB_LIBS_LIST_RELEASE "lib/libz.so.1.2.11")
    list(APPEND ZLIB_LIBS_LIST_DEBUG   "")
    list(APPEND ZLIB_DLLS_LIST_RELEASE "")
    list(APPEND ZLIB_DLLS_LIST_DEBUG   "")
  endif()

  BuildExternal(zlib ${zlib_VERSION} ${zlib_SOURCE_DIR} "${ZLIB_LIBS_LIST_RELEASE}" "${ZLIB_DLLS_LIST_RELEASE}" "${ZLIB_LIBS_LIST_DEBUG}" "${ZLIB_DLLS_LIST_DEBUG}" "")
endmacro()


