include(CMake/BuildExternal.cmake)
include(CMake/BuildAWSSDK.cmake)
include(CMake/BuildJsonCpp.cmake)
include(CMake/BuildFmt.cmake)
include(CMake/BuildCppRestSdk.cmake)
include(CMake/BuildAzure.cmake)
if (BUILD_ZLIB)
  include(CMake/BuildZlib.cmake)
endif()

macro(build3rdparty)
  BuildAwsSdk()
  BuildJsonCPP()
  if (BUILD_ZLIB)
    BuildZlib()
  endif()
  BuildFmt()
  BuildCppRestSdk()
  BuildAzure()
endmacro()
