macro(BuildJsonCpp)
  set(JSONCPP_WITH_TESTS OFF CACHE BOOL "")
  set(JSONCPP_WITH_POST_BUILD_UNITTEST OFF CACHE BOOL "")
  set(JSONCPP_WITH_WARNING_AS_ERROR OFF CACHE BOOL "")
  set(JSONCPP_WITH_STRICT_ISO OFF CACHE BOOL "")
  set(JSONCPP_WITH_PKGCONFIG_SUPPORT OFF CACHE BOOL "")
  set(JSONCPP_WITH_CMAKE_PACKAGE OFF CACHE BOOL "")
  add_subdirectory(${jsoncpp_SOURCE_DIR} ${PROJECT_BINARY_DIR}/jsoncpp_${jsoncpp_VERSION})
  target_compile_options(jsoncpp_lib_static PRIVATE "/MD$<$<CONFIG:Debug>:d>")
  set_target_properties(jsoncpp_lib_static PROPERTIES FOLDER ExternalProjectTargets/jsoncpp)
endmacro()

